myapp/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Redis;


Route::get('/', function () {
    echo "Home";
});



Route::group(['prefix' => 'admin'], function () {
    Route::resource('posts', 'PostsController');
});

Route::group(['prefix' => 'blog', 'namespace' => 'Blog'], function () {
    Route::get('/posts', 'BlogController@index')->name('blog.index');
    Route::get('/posts/{id}', 'BlogController@show')->name('blog.show');
    Route::post('/posts/{id}/comment', 'BlogController@comment')->name('blog.comment');
    Route::get('/posts/{id}/like', 'BlogController@like')->name('blog.like');
    Route::delete('/posts/{id}', 'BlogController@destroy')->name('blog.destroy');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

myapp/app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable=['content','post_id'];

    protected $guarded=['name','email'];

    public function post()
    {
        return $this->belongsTo(Post::class);
    }

}

myapp/app/Like.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Like extends Model
{

    protected $fillable = ['post_id'];


    public function post()
    {
        return $this->belongsTo(Post::class);
    }

}

myapp/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title', 'content'];

    protected $guarded = ['userId'];

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function likes()
    {
        return $this->hasMany(Like::class);
    }


}

myapp/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];



}

myapp/app/Http/Controllers/Blog/BlogController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Comment;
use App\Forms\LikeForm;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Post;
use App\Forms\CommentForm;

use App\Like;

use Illuminate\Support\Facades\Cache;


class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::withCount('comments')->latest()->paginate(7);
        return view('site.posts.index', compact('posts'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Cache::rememberForever('posts.' . $id, function () use ($id) {
            return Post::withCount('likes')->find($id);
        });
        if (!$post) {
            abort(404);
        }

        $form = \FormBuilder::create(CommentForm::class, [
            'method' => 'POST',
            'url' => route('blog.comment', ['id' => $post->id])
        ]);

        $comments = $post->comments;

        $total_post = $post->comments->count();

        return view('site.posts.show', compact('post', 'form', 'comments', 'total_post'));

    }

    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function comment(request $request, $id)
    {

        $post = Post::findOrFail($id);

        $comment = $post->comments()->create($request->only('content'));

        return redirect()->route('blog.show', ['id' => $post->id]);

    }

    /**
     *
     */
    public function like($id)
    {
        Like::create([
            'post_id' => $id
        ]);

        Cache::forget('posts.' . $id);

        return redirect()->back();
    }


    public function destroy($id)
    {

        $post = Post::findOrFail($id);

        $post->delete();

        \Cache::forget('posts.' . $post->id);

        return redirect()->route('blog.index');

    }


}

myapp/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

myapp/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

myapp/app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers\admin;

namespace App\Http\Controllers;

use App\Forms\PostForm;
use App\Post;

use Illuminate\Http\Request;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();

        return view('site.posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

            $form = \FormBuilder::create(PostForm::class, [
                'method' => 'POST',
                'url' => route('posts.store')
            ]);

            return view('admin.posts.form', compact('form'));

    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $post = Post::create($request->only('title', 'content'));
        return redirect()->route('posts.edit', ['id' => $post->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
            $post = Post::findOrFail($id);
            $form = \FormBuilder::create(PostForm::class, [
                'method' => 'PUT',
                'url' => route('posts.update', ['id' => $post->id]),
                'model' => $post,
            ]);


            return view('admin.posts.form', compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::findOrFail($id);
        $post->update($request->only('title', 'content'));

        \Cache::forget('posts.' . $post->id);

        $action = $request->input('action');

        switch ($action) {
            case 'saveAndReload':
                $return = redirect()->route('posts.edit', ['id' => $post->id]);
                break;
            case 'saveAndClose':
            default:
                $return = redirect()->route('blog.index');
        }
        return $return;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

//        $post = Post::findOrFail($id);
//
//            $post->delete();
//
//            return Redirect::route('blog.index');

    }
}

myapp/resources/views/admin/posts/api.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: user03
 * Date: 4/15/18
 * Time: 10:39 AM
 */

myapp/resources/views/admin/posts/form.blade.php
@extends('layouts.site.main')


@section('content')
    {!! form($form) !!}
@stop

myapp/resources/views/admin/posts/index.blade.php
@extends('layouts.site.main')



@section('content')


    <hr>
    <h3>لیست مطالب منتشر شده</h3>

    @foreach($posts as $post)

        <div class="card border-primary mb-3" style="text-align: right">
            <div class="card-header">

                {{ $post->title }}

                <a href="{{ route('admin.post.edit',$post) }}"style="float: left">ویرایش</a>
            </div>
            <div class="card-body">
                <p class="card-text">{{ $post->content }}</p>
            </div>
        </div>

    @endforeach

@endsection

myapp/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                   لاگین شدید
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

myapp/resources/views/layouts/admin/partials/header.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">
        Laravel
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">

    </div>
</nav>

myapp/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

myapp/resources/views/layouts/site/main.blade.php
<!doctype html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Laravel</title>
    <link rel="stylesheet" href="/css/faltly/style.css">
</head>
<body>
<header>
    @include('layouts.admin.partials.header')
</header>
<main>
    <div class="container">
        @yield('content')
    </div>
</main>
</body>
</html>

myapp/resources/views/site/posts/index.blade.php
@extends('layouts.site.main')

@section('content')
    {{--<h5 class="col-md-12" style="text-align: right">تعداد پست های منتشر شده{{ $posts->total() }}</h5>--}}
    <hr>
    @foreach($posts as $post)
        <div class="card border-primary mb-3" style="text-align: right">
            <div class="card-header">
                <span style="text-align: left; float: left"></span>

                <a href="{{ route('blog.show',$post) }}">{{ $post->title }}</a>

                <p>تعداد کامنت ها {{ $post->comments_count }}</p>





                {{--<a href="{{ route('blog.delete',$post->id) }}">حذف مقاله</a>--}}

                {{--<form method="delete" action="{{  route('posts.destroy',$post->id)  }}">--}}
                    {{--<div class="form-group">--}}
                        {{--<input type="hidden" name="_token" value="{{ csrf_token() }}">--}}

                        {{--<label for="dlt">Delete ID: </label>--}}
                        {{--<input name="id" class="form-control">--}}
                        {{--<div class="form-group">--}}
                            {{--<button type="submit" class="btn btn-primary">Delete</button>--}}
                        {{--</div>--}}
                    {{--</div>--}}
                {{--</form>--}}


            </div>
            <div class="card-body">
                <p class="card-text">{{$post->content}}</p>
            </div>
        </div>
    @endforeach

    {!! $posts->render() !!}

@endsection

myapp/resources/views/site/posts/show.blade.php
@extends('layouts.site.main')

@section('content')

    <hr>

    <div class="jumbotron" style="text-align: right">


        {{--{{ Form::open(['method' => 'DELETE', 'route' => ['blog.delete', $post->id]]) }}--}}
        {{--{{ Form::hidden('id', $post->id) }}--}}
        {{--{{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}--}}
        {{--{{ Form::close() }}--}}


        {{ Form::open(['method' => 'DELETE', 'route' => ['blog.destroy', $post->id]]) }}
        {{ Form::submit('Delete', ['class' => 'btn btn-danger','style'=>'float : left']) }}
        {{ Form::close() }}

        <a href="{{ route('blog.like', ['id' => $post->id]) }}" name="like" methods="get">Like</a>

        <span>تعداد لایک ها{{ $post->likes_count }}</span>

        <h1 class="display-3">{{ $post->title }}</h1>

        <hr class="my-4">

        <p>{{ $post->content }}</p>

    </div>

    <hr>

    <h2>تعداد کامنت ها</h2>

    <h3>{{$total_post}}</h3>

    <h4>کامنت ها</h4>

    {!! form($form) !!}

    @foreach($comments as $comment)

        <div class="jumbotron" style="text-align: right">

            <p>{{ $comment->content }}</p>

        </div>

    @endforeach


@endsection